// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQDNctiIM3ObiXqT_Kq60sNG-7YWsmNGM',
    appId: '1:924308416052:web:62a7ca58d678eec1444c61',
    messagingSenderId: '924308416052',
    projectId: 'flutter-chat-app-8ffe1',
    authDomain: 'flutter-chat-app-8ffe1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8ffe1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5JaSIJaVA1KHPk1oo71BmY_YH2iE0h0',
    appId: '1:924308416052:android:193d581a24b1530a444c61',
    messagingSenderId: '924308416052',
    projectId: 'flutter-chat-app-8ffe1',
    storageBucket: 'flutter-chat-app-8ffe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDynDEl_0OzClw1SFiufgd2sdN2XA3VkNw',
    appId: '1:924308416052:ios:0769f159225c3a0f444c61',
    messagingSenderId: '924308416052',
    projectId: 'flutter-chat-app-8ffe1',
    storageBucket: 'flutter-chat-app-8ffe1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDynDEl_0OzClw1SFiufgd2sdN2XA3VkNw',
    appId: '1:924308416052:ios:0769f159225c3a0f444c61',
    messagingSenderId: '924308416052',
    projectId: 'flutter-chat-app-8ffe1',
    storageBucket: 'flutter-chat-app-8ffe1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQDNctiIM3ObiXqT_Kq60sNG-7YWsmNGM',
    appId: '1:924308416052:web:f61e758437b6c800444c61',
    messagingSenderId: '924308416052',
    projectId: 'flutter-chat-app-8ffe1',
    authDomain: 'flutter-chat-app-8ffe1.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8ffe1.firebasestorage.app',
  );

}